# Change these first
owner: affigame # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/1 * * * *"

sites:
  - name: affigame
    url: https://www.affigame.com
  - name: affigame fivepd 
    check: "tcp-ping"
    url: $SERVER_1
    port: 30130
    icon: https://www.affigame.com/wp-content/uploads/2022/10/affigame5-36x36-1.webp
  - name: affigame Minecraft survie
    check: "tcp-ping"
    url: $SERVER_1
    port: 25565
    icon: https://www.affigame.com/wp-content/uploads/2022/10/affigame5-36x36-1.webp

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.affigame.com
  # baseUrl: /uptime
  logoUrl: https://www.affigame.com/wp-content/uploads/2022/10/affigame5-36x36-1.webp
  name : status affigame
  introTitle: "**affigame** est une communauté basser sur les jeux vidéo "
  introMessage: visite le site https://www.affigame.com pour nous rejoindre
  navbar:
    - title: Status
      href: /
    - title: site web affigame
      href: https://www.affigame.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
